version: '3.8'

services:
  db:
    image: postgres:12-alpine
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
